### Requirements
# Playwright
# BS4
# Pandas


### Auto Code Gen by interacting with the website (terminal command)
# playwright codegen https://bund.jobboerse.gv.at/sap/bc/jobs/index.html

### Necessary libraries
from playwright.sync_api import sync_playwright
from bs4 import BeautifulSoup
import re
import pandas
import os

### Actual scraper code
 ## STEP 1: Duplicate Checking
    # Read in the json to access the unique reference IDs in order to check for duplicates and avoid reading in jobs that already exist in the JSON
try:
    df_jobs = pandas.read_json("jobs_scraped.json", encoding = "utf-8")
    id_lists = df_jobs["Unique_ID"].tolist()
except:
    id_lists = []
print(id_lists)
# Make sure the data folder exists in order to save the relevant PDFs
os.makedirs("data", exist_ok = True)

### STEP 2: Open up chromium and prepare the variables
with sync_playwright() as p:
    browser = p.chromium.launch(headless = False)
    page = browser.new_page()
    page.goto("https://bund.jobboerse.gv.at/sap/bc/jobs/index.html")
    while (True):
        try:
            page.get_by_role("button", name="Die nächsten Ergebnisse").click(timeout = 1000)
            #page.wait_for_timeout(2)
        except Exception:
            break
    count = len(id_lists)
    df = pandas.DataFrame
    scraped_jobs = []
    # This try is there to save everything we did up until a point of failure (website not loading etc.)
    try:
        while (True):
                try:
                    while (True):
                        try:
                            page.get_by_role("button", name="Die nächsten Ergebnisse").click(timeout = 1000)
                        except Exception:
                            break
                    ## STEP 3: Scrape the relevant data
                    locator_index = f"[id=\"__item7-__clone{count}-content\"]"
                    # Hardcoded time out, because wait for loaded state does not work
                    page.locator(locator_index).click()
                    page.wait_for_timeout(3000)
                    ### Check for duplicates
                    if page.locator("text='Referenzcode:'").locator("xpath=following-sibling::*[1]").inner_text().strip() in id_lists:
                        print("Duplicate found")
                        count += 1
                        page.goto("https://bund.jobboerse.gv.at/sap/bc/jobs/index.html")
                        continue
                    # Use playwright to extract the necessary datapoints. Soup was considered as an alternative, but the resulting HTML is massive and very user unfriendly.
                    # First, title and general summary
                    title = page.locator("[id=\"__title9-inner\"]").inner_text()
                    general_summary = page.locator("[id=\"__box1\"]").inner_text()
                    # Second, the Grunddaten
                    # Best to store this as a dictionary: Use soup to extract the html based box content
                    box_html = page.locator('[id="__html5"]').inner_html()
                    soup = BeautifulSoup(box_html, "html.parser")
                    base_data = {}

                    # This part is generated by AI and verified by the Author
                    labels = soup.find_all(text=re.compile(r":\s*$"))
                    for label in labels:
                        key = label.strip().rstrip(":")
                        parent = label.parent
                        # Grab the adjacent element's text
                        val_elem = parent.find_next_sibling()
                        if val_elem and key:
                            base_data[key] = " ".join(val_elem.get_text().split())
                    # End of Vibe Coded part

                    # Use the SAP Reference ID as its own value for PDF naming and efficiency checking
                    Unique_ID = base_data["Referenzcode"]

                    ### These fields can potentially not be included in a job search and thus can be empty!
                    # Aufgaben und Tätigkeiten
                    try:
                        page.get_by_role("form", name="Aufgaben und Tätigkeiten").get_by_label("Expandieren/komprimieren").click(timeout=1000)
                        activities =  page.locator("[id=\"__html6\"]").inner_text()
                    except:
                        activities = ""
                        pass
                    # Requirements
                    try:
                        page.get_by_label("Erfordernisse").get_by_role("button", name="Expandieren/komprimieren").click(timeout=1000)
                        requirements = page.locator("[id=\"__html7\"]").inner_text()
                    except:
                        requirements = ""
                        pass
                    # PDF URL, always needs to be included, else error
                    with page.expect_popup() as page1_info:
                        page.get_by_role("button", name="Druckvorschau").click()
                    page1 = page1_info.value
                    page1.wait_for_load_state()
                    URL_Link_PDF = page1.url
                    # Download the PDF and give it the unique ID as the name
                    try:
                        response = page.request.get(URL_Link_PDF)
                        if response.status == 200:
                            with open(f"data/{Unique_ID}.pdf", "wb") as f:
                                f.write(response.body())
                        else:
                            print(f"Could not download PDF file for {title}, {Unique_ID}")
                    except:
                        pass
                    page1.close()
                    ## STEP 4: Save the scraped data into a list and then convert it to a dataframe
                    job_instance = {
                        "Job Title " : title,
                        "Job General Summary" : general_summary,
                        "Base Data" : base_data,
                        "Job activites" : activities,
                        "PDF URL" : URL_Link_PDF,
                        "Unique_ID" : Unique_ID
                    }
                    scraped_jobs.append(job_instance)
                    count += 1
                    page.goto("https://bund.jobboerse.gv.at/sap/bc/jobs/index.html")
                    page.wait_for_load_state()
                except:
                    break
    except:
        pass
            
    
    df = pandas.DataFrame(scraped_jobs)
    if os.path.exists("jobs_scraped.json"):
        final_df = pandas.concat([df_jobs, df], ignore_index = True)
        final_df.to_json(
            "jobs_scraped.json", 
            orient = "records", 
)
    else:
        df.to_json("jobs_scraped.json", orient = "records")

    # You can step through line-by-line from the Inspector UI
    browser.close()